# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivosform'),
        ),
    ]
